### ISSUE TITLE
Creating framework for iOS

### ISSUE THREAD

**Issue by AMConsulting** [lnxbil/GPhoto2.framework#2]
Hi Andreas,
there's a way to create the framework in order to use it for iOS applications?
Many thanks in advance.
Best regards

Angelo

**Comment by dvdhpkns** [comment]
Hi @xaphod did you ever figure out a way to get gphoto2 to play nice with iOS, or did you abandon that idea and go a different route?

**Comment by xaphod** [comment]
@dvdhpkns Wrote my own. Used gphoto2 for a bit of inspiration and to see some of the hex codes, but largely reverse-engineered it from wireshark / packetdumps

**Comment by xaphod** [comment]
(result -> https://wifibooth.com)

**Comment by lnxbil** [comment]
Nice work!

Is there a way to connect a non-wireless camera? Some RPi server to use for cable-based cameras? I still have a CF-based camera without WiFi capability.

**Comment by xaphod** [comment]
Thanks. Am thinking of adding CamFi support. But not sure.

**Comment by dvdhpkns** [comment]
@xaphod really cool app! Have you come across the issue with Canon cameras where you get the error "Connection target not found"? I've noticed that after using gphoto to issue any command I get this error and then have to reconnect to the camera, but with your app, I rarely see that error. Are you doing something special to keep the connection alive and avoid this?
In regards to CamFi, integration in your app would be pretty straight forward, they communicate with their app using HTTP API, so no PTP. There are some crappy docs in Chinese that chrome can translate for you [here](http://www.cam-fi.com/sdk/sdk_restapi.html), but it's probably easier just to launch their app and use charles proxy or fiddler to see the commands. You can also check out [WeyeFeye](https://xsories.com/weye-feye) which is a cheaper alternative that you can integrate with and recommend to your users. It uses an API similar to camfi.

**Comment by xaphod** [comment]
@dvdhpkns thanks. "Connection target not found" is just Canon-speak for "connection terminated", which can happen for a variety of reasons. Perhaps your camera isn't supported, and one end terminates the connection when an invalid command or response is received. If you are seeing successful commands & responses then after some amount of time, the connection drops, then that's different - i'm assuming gphoto is doing standard PTP stuff like holding the separate event socket open and ping/pong'ing; wifibooth also periodically does PTP_check_event to look for new photos.
Yeah, CamFi won't be hard but I haven't had time yet, it's still on the list...

**Comment by dvdhpkns** [comment]
@xaphod what I am seeing with gphoto is a successful command runs and then it drops the connection immediately after one command is run every time. I'm assuming this is because they are not keeping the connection open and ping/pong'ing, and are instead just running a command and closing the connection. This is helpful, thanks!

**Comment by xaphod** [comment]
That doesn't sound like an issue with keeping the connection open, it
sounds like one end is actively dropping the connection because it received
something it did not like.
Good luck
