### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by bvanderw** [lnxbil/GPhoto2.framework#6]
Thanks for this!

Using Xcode 9.2 on High Sierra, I encountered the following issues:

To build pkgconfig, the build script needed to be modified so that --with-internal-glib is passed to configure.

To build libusb-compat, I had to install both autoconf and automake (using HomeBrew).

To build libgphoto2, I had to run the following before executing the build script:

export PATH=${PATH}:/usr/local/opt/gettext/bin

This was all required to build the versions specified in the config file, but I was then also able to build the framework using the latest versions:

pkgconfig 0.29.2
libusb 1.0.22
libgphoto2 2.5.17

**Comment by lnxbil** [comment]
I just updated to 10.15 build target an added the new requirements to the `README.md`.
