### ISSUE TITLE
Unable to run build.sh

### ISSUE THREAD

**Issue by rs9100448** [lnxbil/GPhoto2.framework#8]
Hi,
    I'm trying to run build.sh file which is giving an error. Can you please help me out to resolve it?

Build Process of the GPhoto2.framework
https://github.com/lnxbil/GPhoto2.framework

+ Checking permissions on /Library/Frameworks/GPhoto2.framework
+ Download and extracting files
+ Start building at Tue Jul 20 12:27:18 IST 2021 with 16 threads
  - Building libtool-2.4.6

An error occured
(Full Log at /Users/rohitJft/Downloads/GPhoto2.framework-master 2/download/logs/libtool-2.4.6_buildlog-20210720_122702.log):

==> /Users/rohitJft/Downloads/GPhoto2.framework-master <==
tail: 2/download/logs/libtool-2.4.6_buildlog-20210720_122702.log: No such file or directory

**libtool-2.4.6_buildlog-20210720_122702.log** is created but it's unable to detect it 

Thank you

**Comment by lnxbil** [comment]
Oh yeah ... there is a space in your directory and I did not took care of it in the code. Easiest fix would be to rename your folder `GPhoto2.framework-master 2` (strip ` 2`), but you may also have that folder already.

**Comment by rs9100448** [comment]
Build Process of the GPhoto2.framework
https://github.com/lnxbil/GPhoto2.framework

+ Checking permissions on /Library/Frameworks/GPhoto2.framework
+ Download and extracting files
+ Start building at Tue Jul 20 13:00:28 IST 2021 with 16 threads
  - Building libtool-2.4.6
  - Building pkg-config-0.29.2

An error occured
(Full Log at /Users/rohitJft/Documents/Gphoto2DemoProjects/GPhoto2.framework-master/download/logs/pkg-config-0.29.2_buildlog-20210720_130009.log):

configure: WARNING: sys/wait.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: sys/wait.h: proceeding with the compiler's result
checking for sys/wait.h... yes
checking malloc.h usability... no
checking malloc.h presence... no
checking for malloc.h... no
checking for bash... /bin/bash
checking for default search path for .pc files... ${libdir}/pkgconfig:${datadir}/pkgconfig
checking for system include path to avoid -I flags... /usr/include
checking for system library path to avoid -L flags... /usr/lib:/lib
configure: creating ./config.lt
config.lt: creating libtool
checking whether to list both direct and indirect dependencies... no
checking for Win32... no
checking if prefix should be redefined at runtime... no
checking if internal glib should be used... no
checking for pkg-config... /usr/local/bin//pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for glib-2.0 >= 2.16... no
configure: error: Either a previously installed pkg-config or "glib-2.0 >= 2.16" could not be found. Please set GLIB_CFLAGS and GLIB_LIBS to the correct values or pass --with-internal-glib to configure to use the bundled copy.


After renaming I'm getting another error. May I know the reason for the error in the logs?

**Comment by lnxbil** [comment]
The error is written there: you don't have `glib` installed. I don't know why it is necessary, but unless it is installed and incorpored into the install, I support it'll not work.

Also, the newest GPhoto2 can also not be compiled on MacOS, I just tried.

**Comment by rs9100448** [comment]
Do you mean, I can't use it in my project. Actually, I was building a macOS app which it using Gphoto2. It's working fine while debugging mode but when I make an archive using developer ID then it's unable to load the library.

**dyld: Library not loaded: /Library/Frameworks/GPhoto2.framework/prefix/lib/libgphoto2.6.dylib
  Referenced from: /Users/rohitJft/Library/Developer/Xcode/DerivedData/GPhoto2FrameworkInfo-ehkvjdzwveqqkodyqdheixlptalw/Build/Products/Debug/GPhoto2FrameworkInfo.app/Contents/MacOS/GPhoto2FrameworkInfo
  Reason: no suitable image found.  Did find:
	/usr/local/lib/libgphoto2.6.dylib: code signature in (/usr/local/lib/libgphoto2.6.dylib) not valid for use in process using Library Validation: not allowing mapping of development code into production process**

See the exception. 
Suggest me something because my whole app has been built but making the delivery is a hassle due to not being able to load the library. 

I also try to use the Python-gphoto2 package but the same issue occurs.

Python library not found. Set the PYTHON_LIBRARY environment variable with the path to a Python library.

Please suggest me something.

**Comment by lnxbil** [comment]
Are you planning in distributing the App via the MAS? It will be rejected, because GPhoto2 uses low-level USB access

**Comment by rs9100448** [comment]
Yeah but I'm distributing it as a .pkg file (apple notarize).  Unsigned .app is loading the library but whenever I'm making it signed .app with the help Developer ID (apple notarize). It's not loading the library.  Is there any way to distribute the app, not on the app store?

**Comment by lnxbil** [comment]
Before the new security measurements a few years ago, it was easy, but I don't know about today. It worked almost one year ago, as I tried it the last time. I also have to say that I switched to QT, which is much easier with porting and loading dylib files than it is with Apple Frameworks files. With QT, you can pack the dylib files and change the loader parameters to have them all bundled in one App.

I created this wrapper framework over 10 years ago and it worked as it should. You still had (or maybe have) to kill the PPTPCamera driver manually to connect it to GPhoto2.

**Comment by rs9100448** [comment]
> I created this wrapper framework over 10 years ago and it worked as it should. You still had (or maybe have) to kill the PPTPCamera driver manually to connect it to GPhoto2.

I can easily connect with the camera and I didn't have to kill the PTPCamera process.  So the basic conclusion is that we can not distribute our app using Gphoto2?

Do me a favour that if you have 10-15 leisure time then can we have a call. Just show you accurate problem may I'm unable to exact problem.

**Comment by lnxbil** [comment]
> > I created this wrapper framework over 10 years ago and it worked as it should. You still had (or maybe have) to kill the PPTPCamera driver manually to connect it to GPhoto2.
> 
> I can easily connect with the camera and I didn't have to kill the PTPCamera process. So the basic conclusion is that we can not distribute our app using Gphoto2?

Good to know that it's working as it should be.

> Do me a favour that if you have 10-15 leisure time then can we have a call. Just show you accurate problem may I'm unable to exact problem.

We can, but I do not know if I can help you with code-signing questions, I haven't been involved with code signing in Apple for many years and it was only on the iPhone/iPad. I also do not have a valid developer certificate anymore, so I cannot test stuff on my end.

Concerning a call: Please mail me (email is e.g. in the commit messages on github), so that we can arrange something. I'm on CES(T) time.

**Comment by rs9100448** [comment]
Let me know your leisure time of tomorrow. So I can arrange a meeting. I'm on IST time.   

> Please mail me (email is e.g. in the commit messages on github),

please let me know your email because I'm unable to find it.
