### ISSUE TITLE
Do you have the iOS version?

### ISSUE THREAD

**Issue by SiuyuenChow** [lnxbil/GPhoto2.framework#9]
Hello,

Recently I was working on the iOS version of Gphoto2 and had some problems.

After I downloaded the source code for gphoto2, I tried to process it.

Here are my steps:
1. cd /libgphoto2-2.5.10
2.  ./configure
3. make
![image](https://user-images.githubusercontent.com/12928929/180276364-9465c83b-c8f2-4dad-8667-f0d3c368bd66.png)

Then I get libgphoto2_port.dylib
![image](https://user-images.githubusercontent.com/12928929/180276289-4a3dce70-ee8e-46f2-b39b-5a9ad1835bcd.png)

Am I doing the right thing?
![image](https://user-images.githubusercontent.com/12928929/180276396-5b6c0a9a-d3ab-480a-b720-4298ee9d13a1.png)

Looking forward to your reply.

Siu

Thank you

**Comment by lnxbil** [comment]
Hi, I haven't tried building the iOS version for many years. At the time this worked, it was on the first iPad version and only with jailbreak. I have no idea if this still works and I cannot try it, I haven't been enrolled in the iPhone Developer program also for years.

**Comment by SiuyuenChow** [comment]
> Hi, I haven't tried building the iOS version for many years. At the time this worked, it was on the first iPad version and only with jailbreak. I have no idea if this still works and I cannot try it, I haven't been enrolled in the iPhone Developer program also for years.

Recently, I am working on the iOS version. There is very little information in this respect. I would like to find some experienced people to communicate with. Is it convenient?
My email is ...

**Comment by lnxbil** [comment]
Have you read #2?

**Comment by SiuyuenChow** [comment]
> Have you read #2?

I need to read it.

**Comment by lnxbil** [comment]
Closing the issue, this repo is about the MacOS version, not iOS.
